apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturertessera
  namespace: manufacturer-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturertessera
  helmVersion: v3
  chart:
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1759
    path: platforms/hyperledger-besu/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: manufacturer-bes
      labels:
    images:      
      alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.1.1
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
    tessera:
      name: manufacturer-tessera
      dbname: demodb      
      dburl: "jdbc:mysql://manufacturer-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
 
      url: "https://manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:443"
      
      clienturl: "https://manufacturer-tessera:8888"
      othernodes:
        - url: https://carrier.rc.dev2.aws.blockchaincloudpoc-develop.com
      trust: "TOFU"
      
      
      servicetype: ClusterIP
      ports:
        tm: 443        
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: manufacturer-ambassador-certs
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/manufacturer-bes/crypto/manufacturer
      serviceaccountname: vault-auth
      keyname: credentials
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besumanufacturer
 
    proxy:
      provider: "ambassador"
      external_url: manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
