apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1770
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"GfctS5b2eDLnZ2daM6dBHp","role":"0","verkey":"9YEEK8GnxXYzV8wHQscY2e3bL4453deUumTX7xs8fiLV"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"NN5itRxhNsUGDB5qQJUzfu","role":"0","verkey":"CeLomPfu5Ja6veByKrhmsQUrGx9gH8QFGwYA4oUDgtGd"},"metadata":{"from":"GfctS5b2eDLnZ2daM6dBHp"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"9mGuehKJijecz8tZyo4aN1","role":"2","verkey":"5n2Z12gH76Mnb6x9xMhhTU4Gh3ecKSNhaY3xFhc2qgr7"},"metadata":{"from":"NN5itRxhNsUGDB5qQJUzfu"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"86yuhmWzc62K8RKJkhxHud","role":"2","verkey":"4sYYAp7Pocfe6A2ycjwWVcwRe9D2N685m9jsva7m3vzk"},"metadata":{"from":"NN5itRxhNsUGDB5qQJUzfu"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"4XaQoEQ6RsicwzksSrKFck","role":"0","verkey":"2vW41d588UZtoqDZQW827vVvwEGZrYVBSjfecEutgfmU"},"metadata":{"from":"GfctS5b2eDLnZ2daM6dBHp"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"7pqQZxm5jF8fCv9HTL1vz5","role":"2","verkey":"4ik7V7FhrqRGxdwa732tXKQcky7oHhWDEua8hSN1hU2f"},"metadata":{"from":"4XaQoEQ6RsicwzksSrKFck"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"EYcWv6ojaT3W1FHa1AjSWP","role":"2","verkey":"8PBknJyLkKdUXcmYK428b8G73fUKm24Fvg98n4SvET6N"},"metadata":{"from":"4XaQoEQ6RsicwzksSrKFck"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
