apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: employer-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: employer-ns
spec:
  releaseName: employer-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1770
  values:
    metadata:
      name: employer-dtg
      namespace: employer-ns
    organization:
      name: employer
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"WAioZNb93UUdjT1xetaMja","role":"0","verkey":"Gu3dPyz7fxUM3VrekGAjP8dkW4bNcQkPuD1QMq7HdWNh"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"MP5YEBqioPtyUoGSwrCFFU","role":"0","verkey":"C7Gpn8zNKuToGgf5MkPfiwTNS9Wh6kxzTycjEZ6rEmru"},"metadata":{"from":"WAioZNb93UUdjT1xetaMja"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"NtQywh83bZLb8k5cRHqv9C","role":"2","verkey":"CvsfRtnSsTFS1dt3xotGjCMB8iw24QmAkTpXSbZu8XPZ"},"metadata":{"from":"MP5YEBqioPtyUoGSwrCFFU"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"QxuHcnpY9YvdiDWP1rmZAh","role":"2","verkey":"E4YXX4JzgHefia1imkuiYVy7j6gBTde3v4tUesMTrMPs"},"metadata":{"from":"MP5YEBqioPtyUoGSwrCFFU"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"SemHfQ12d4dqfSQV6TQAov","role":"0","verkey":"Eyt96MXmq9KNSACxRhr7zAcSvQb7pqw9KVPRYSddjs9p"},"metadata":{"from":"WAioZNb93UUdjT1xetaMja"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"Hs2mijTyLeMeJxmBUaJ1ok","role":"2","verkey":"AC4UT8h7he3svKPPenRsi3Vtu4w67xJj5SxcTBm9RirJ"},"metadata":{"from":"SemHfQ12d4dqfSQV6TQAov"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"95LRNV3cvRNEDiA63FDWnz","role":"2","verkey":"5QFzGAbaNHgszpvA6HCNa42PJBB1sCZ4pzgJahyQb9G4"},"metadata":{"from":"SemHfQ12d4dqfSQV6TQAov"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
