apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-tessera-job
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: store-tessera-job
  chart:
    path: platforms/hyperledger-besu/charts/tessera_key_mgmt
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1759
  values:
    metadata:
      name: store-tessera-job
      namespace: store-bes
    peer:
      name: store        
    image:      
      repository: quorumengineering/tessera:21.1.1
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: besustore
      role: vault-role
      keyprefix: store-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/store-bes/crypto
