apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zone
  annotations:
    fluxcd.io/automated: "false"
  namespace: svd-ent
spec:
  releaseName: zone
  chart:
    path: platforms/r3-corda-ent/charts/zone
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: develop
  values:
    metadata:
      namespace: svd-ent
      nodeName: zone
      prefix: svd
    image:
      initContainer: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      zoneContainer: adopblockchaincloud0502.azurecr.io/corda/enterprise-zone:1.5.1-zulu-openjdk8u242
      pullPolicy: IfNotPresent
      imagePullSecrets: 
        - name: "regcred"
    config:
      volume:
        baseDir: /opt/cenm
      pvc:
        volumeSizeZoneH2: 1Gi
        volumeSizeZoneLogs: 1Gi
        volumeSizeZoneData: 1Gi
      pod:
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
      zoneJar:
        path: bin
    cenmServices:
      idmanName: idman
      authName: auth
      authPort: 8081
    database:
      driverClassName: "org.h2.Driver"
      jdbcDriver: ""
      url: "jdbc:h2:file:./h2/zone-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
      user: "example-db-user"
      password: "example-db-password"
      runMigration: true
    service:
      type: ClusterIP
      port: 80
    listenerPort:
      enm: 25000
      admin: 12345
    storageClass: cordaentsc
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authPath: cordaentsvd
      serviceAccountName: vault-auth
      certsecretprefix: secretsv2/data/svd
      retries: 10
      sleepTimeAfterError: 15
