kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: university-aws-storageclass
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  encrypted: "true"
allowedTopologies:
  - matchLabelExpressions:
    - key: failure-domain.beta.kubernetes.io/zone
      values:
      - eu-west-1a
