##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
dependencies:
  - role: "setup/geth"
  - role: "setup/bootnode"
