apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-surpar-peer0
  namespace: surpar-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: joinchannel-peer0-join-allchannel-surpar-peer0
  chart:
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1770
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: surpar-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.surpar-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: surparMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: surfabsurpar-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/surpar-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/surpar-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer11.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
