apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-authority-trustee-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-authority-trustee-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1770
  values:
    metadata:
      name: authority-authority-trustee-auth-job
      namespace: authority-ns
    network:
      name: baf
      kubernetes_url: https://34D2F36E71F0880BE63D943D2E503A9B.gr7.eu-west-1.eks.amazonaws.com
    image:
      name: authority
      repository: alpine:3.9.4
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      identity: authority-trustee
      admin_auth_path: kubernetes-authority-admin-auth
      policy: authority-authority-trustee-ro
      policy_content: path \"/authority/data/trustees/authority-trustee/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-authority-authority-trustee-auth
    account:
      admin_service: authority-admin-vault-auth
      admin_role: rw
      service: authority-authority-trustee-vault-auth
      role: ro
