apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: auth-auth-trustee
  annotations:
    fluxcd.io/automated: "false"
  namespace: auth-ns
spec:
  releaseName: auth-auth-trustee
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/surabhi-dudhediya/blockchain-automation-framework.git
    ref: indy
  values:
    metadata:
      name: auth-auth-trustee
      namespace: auth-ns
    network:
      name: baf
    image:
      name: auth
      repository: adopblockchaincloud0502.azurecr.io/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      version: "2"
      keyPath: auth.trustees
      identity: auth-trustee
      auth_path: kubernetes-auth-admin-auth
    account:
      service: auth-admin-vault-auth
      role: rw
