apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: partner-admin-vault-auth-cluster-admin-role-binding
  namespace: partner-ns
  labels:
    organization: partner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: partner-admin-vault-auth
  namespace: partner-ns
