apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainvalidator3ibft
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator3ibft
  chart:
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1759
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://fdc95d6ec427b1ffbb9da9ee09583cc402fbad27e87b48487ee01527e4eef7de339f0a2d3addc43a7099a214cebf6cc674180df1210b9b505cf51b94dd5aa041@validator1.rc.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://74d8bef0aade11dedee1519fb2339aa26ca08262abc7d47e981c1a518891c56d5eb47d715641dbcf54a03c813952b00000ebe0a1f8e97220cd25ecd51aa05c27@validator2.rc.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://c49be75ad186b690a8eba4001596ba264cff65ff3be3fa38c24c95eb9869b8895763ebc41c360bb146bad3c72eead2f7e5a45c1c3f98e3fa012e11aee82d22bd@validator3.rc.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://8a7909287fc925618d99999ca10a14575a45852bbc3362b3718b03702fa45030e73bf9f2c883e6612d94a7fa843672728da17d733de6ca4642fc1d2339e1fba4@validator4.rc.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://187a37f11f50a96ef8574ebbba4e9312787a88dce4a31ea4cbb92ba24e60ee89f5110ce684d85b6685acf0ef3fd30aec4a61fc8dbc3682c9d591b4a809413017@carrier.rc.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://ecbdb5043edb07691732e05758120beded9de6cb0fadc8b040c780b6b55f67438231c5fbf3f3f5eff08c70d3e883f48ff46f2d922708207664e44d1043ad634e@manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:15051"
      
      - "enode://c2aca6aabeb97f7e90254248087ce0ba8a5ef3caae294859a99c7f92f4ce9b1868a7041cdcde8b48acf98076c047ec47adace323ed0023ef43f983e8d2b0a8d6@store.rc.dev2.aws.blockchaincloudpoc-develop.com:15053"
      

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychain.rc.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15045
      rpc: 15046

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator3
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychain-bes/crypto/validator3
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGU5NjhjZDU3MmU4NGRhMjlkODYyYTRkOGQzM2I3YjE1OTc2MWE1NDE5NGVmNmU3OTI3YWYyNTdiNTc3YjI0ODNhMmM0MDNjZDQ5MjExMWI0N2Q5NDNjNjllOGJmODU2OWZkZjhmNjRkMTU1NWFmZDkyMDZmYjc2MDg5OWI5NDBmMTRiNjEwNDViYmEyN2ZjZDUwMmZjMzc5YmEyYzgyNDhjOGY5NmM4MDg0MDAwMDAwMDBjMCIKfQ==
