apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: schain-ns
spec:
  releaseName: notary-initial-registration
  chart:
    path: platforms/r3-corda/charts/notary-initial-registration
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1770
  values:
    nodeName: notary
    replicas: 1
    metadata:
      namespace: schain-ns  
    image:
      containerName: adopblockchaincloud0502.azurecr.io/corda:4.7-linuxkit
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.rc.dev2.aws.blockchaincloudpoc-develop.com
      networkmapCertAlias: networkmap.rc.dev2.aws.blockchaincloudpoc-develop.com
    nodeConf:
      p2p:
        url: notary.schain-ns
        port: 10002
      ambassadorAddress: notary.rc.dev2.aws.blockchaincloudpoc-develop.com:15031
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: True
        serviceLegalName: O=Notary Service,OU=Notary,L=London,C=GB
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: notarydb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarydb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmap.rc.dev2.aws.blockchaincloudpoc-develop.com
      doormanURL: https://doorman.rc.dev2.aws.blockchaincloudpoc-develop.com
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryoperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordanotary
      serviceaccountname: vault-auth
      dbsecretprefix: notary/data/credentials/database
      rpcusersecretprefix: notary/data/credentials/rpcusers
      keystoresecretprefix: notary/data/credentials/keystore
      certsecretprefix: notary/data/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
