apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1770
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"WVPRkiPZzpMs7iawmuHTdQ","role":"0","verkey":"H5DhH58fZrrA3RHzWAukgrroeiCb9HXHwPMpe86k1twB"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"NnGSciXK1KVS98wKQ7WCzq","role":"0","verkey":"3nL5CpscdMDFi7ZQwgyibLco5itnPPsUd9YhSvWwUB3F"},"metadata":{"from":"WVPRkiPZzpMs7iawmuHTdQ"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"Xiupakz5X4MRiJNH8uewWg","role":"2","verkey":"HkCiBFCBAmvWF32FGHZ7X83SipFhFLgVtzCNMzSRR2Ab"},"metadata":{"from":"NnGSciXK1KVS98wKQ7WCzq"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"BxNTcHchETLAx3VQ57rd5N","role":"2","verkey":"6yJJG5nRik7YikZo7EZXb9vmWqj597Mr6gekewseps6c"},"metadata":{"from":"NnGSciXK1KVS98wKQ7WCzq"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"MTjwhLcg8xCW9i9yfPq8Y1","role":"0","verkey":"C9pCoV35gKPj8vDAnfbzgTvLMH7XoWpV8br1rA31ann3"},"metadata":{"from":"WVPRkiPZzpMs7iawmuHTdQ"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"RDypp5jKn5Qz3bYAn9pe1f","role":"2","verkey":"ECmBPEgtZQR2bCiAMvai3B7rsKocdsj4zMomweYuHJ6e"},"metadata":{"from":"MTjwhLcg8xCW9i9yfPq8Y1"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"4AdsoZbB9sRnhoXBww5JMz","role":"2","verkey":"2j66Bhi6V6Zo4HHpiYdTvszwWB2GWXNTezTWqfJw2ULU"},"metadata":{"from":"MTjwhLcg8xCW9i9yfPq8Y1"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
