apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mnfsvd
  namespace: mnfsvd-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mnfsvd
  chart:
    git: https://github.com/surabhi-dudhediya/bevel.git
    ref: feature-1759
    path: platforms/r3-corda-ent/charts/node
  values:
    nodeName: mnfsvd
    metadata:
      namespace: mnfsvd-ent
      labels:
    image:
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      nodeContainerName: adopblockchaincloud0502.azurecr.io/corda/enterprise-node:4.7
      imagepullsecret: regcred
      pullPolicy: Always
    acceptLicence: true
    storage:
      name: cordaentsc
    replicas: 1
    networkServices:
      doormanURL: https://idmsvd.rc.dev2.aws.blockchaincloudpoc-develop.com
      networkMapURL: https://nmapsvd.rc.dev2.aws.blockchaincloudpoc-develop.com
      idmanDomain: "idmsvd.rc.dev2.aws.blockchaincloudpoc-develop.com"
      networkMapDomain: "nmapsvd.rc.dev2.aws.blockchaincloudpoc-develop.com"
      idmanName: "idmsvd"
      networkmapName: "nmapsvd"
    firewall:
      enabled: False      
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordaentmnfsvd
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/mnfsvd/mnfsvd
      nodePath: mnfsvd
      retries: 30
      retryInterval: 30
    cordapps:
      getcordapps: true
      jars:
        - url: 
        - url: 
        
    nodeConf:
      ambassador:
        external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
        p2pPort: 15035
        p2pAddress: mnfsvd.rc.dev2.aws.blockchaincloudpoc-develop.com:15035
      legalName: "O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH"
      emailAddress: "dev-node@bevel.com"
      crlCheckSoftFail: true
      tlsCertCrlDistPoint: ""
      tlsCertCrlIssuer: "CN=Corda TLS CRL Authority,OU=Corda UAT,O=R3 HoldCo LLC,L=New York,C=US"
      devMode: false
      volume:
        baseDir: /opt/corda/base
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 1524
        unit: M
      pod:
        resources:
          limits: 1524M
          requests: 1524M
    service:
      p2pPort: 10002
      p2pAddress: mnfsvd.mnfsvd-ent
      messagingServerPort: 10002
      ssh:
        enabled: true
        sshdPort: 2222
      rpc:
        port: 30000
        adminPort: 30009
        users:
        - name: mnfsvd
          password: mnfsvdP
          permissions: ALL
    dataSourceProperties:
      dataSource:
        user: mnfsvd-db-user
        password: mnfsvd-db-password
        url: "jdbc:h2:tcp://mnfsvddb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dbUrl: "mnfsvddb"
        dbPort: 9101
      monitoring:
        enabled: true
        port: 8090
      allowDevCorDapps:
        enabled: true
      retries: 20
      retryInterval: 15
    sleepTimeAfterError: 120
    sleepTime: 0
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
