##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build bevel-build docker image triggered by :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags
#
# Build corda os docker image triggered by :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags

name: Docker images build

on:
  create:
  push:
    branches:
        - develop
    paths:
      - 'Dockerfile'        
      - 'Dockerfile.jkd8'
      - 'platforms/r3-corda/images/**'   
      - 'examples/supplychain-app/quorum/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # on push to develop branch, create docker tags latest and jdk8-latest
  bevel-build-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Login to the container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    -
      name: Build and push release tag latest
      id: docker_build_latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}-latest
    -
      name: Build and push tag jdk8-latest
      id: docker_build_jdk8_latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./Dockerfile.jdk8
        push: true
        tags: ${{ steps.meta.outputs.tags }}-jdk8-latest

  # on tag vx.y.z created, create docker tag stable, x.y.z and jdk8
  bevel-build-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to the container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    -
      name: Build and push release tag ${{ steps.vars.outputs.tag }}  
      id: docker_build_release
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}-${{ steps.vars.outputs.tag }}    
    -
      name: Build and push release tag stable based on v${{ steps.vars.outputs.tag }}
      id: docker_build_stable
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}-stable          
    -
      name: Build and push tag jdk8-latest
      id: docker_build_jdk8
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: ./Dockerfile.jdk8
        push: true
        tags: ${{ steps.meta.outputs.tags }}-jdk8-stable

  cordaOS-latest: 
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to the container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - 
      name: corda builds
      run: |
        WDIR=`pwd`
        
        java -version
        update-alternatives --list java

        echo "---- building networkmap ----"
        cd ${WDIR}/platforms/r3-corda/images/networkmap
        mvn clean install -DskipTests   

        echo "---- building doorman ----"
        cd ${WDIR}/platforms/r3-corda/images/doorman
        mvn clean install -DskipTests  
    -
      name: Build and push cordaOS doorman latest  
      id: corda_doorman_latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: platforms/r3-corda/images/doorman
        push: true
        tags: ${{ steps.meta.outputs.tags }}-corda-doorman-linuxkit-latest            
    -
      name: Build and push cordaOS networkmap latest
      id: corda_networkmap_latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: platforms/r3-corda/images/networkmap
        push: true
        tags: ${{ steps.meta.outputs.tags }}-corda-networkmap-linuxkit 
    -
      name: Build and push cordaOS node latest 
      id: corda_node_latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: platforms/r3-corda/images/Dockerfile-corda-tls
        push: true
        tags: ${{ steps.meta.outputs.tags }}-corda-latest 
  
  cordaOS-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to the container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - 
      name: corda builds
      run: |
        WDIR=`pwd`
        
        java -version
        update-alternatives --list java

        echo "---- building networkmap ----"
        cd ${WDIR}/platforms/r3-corda/images/networkmap
        mvn clean install -DskipTests   

        echo "---- building doorman ----"
        cd ${WDIR}/platforms/r3-corda/images/doorman
        mvn clean install -DskipTests  
    -
      name: Build and push cordaOS doorman release tag ${{ steps.vars.outputs.tag }}  
      id: corda_doorman_release
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: platforms/r3-corda/images/doorman
        push: true
        tags: ${{ steps.meta.outputs.tags }}-corda-doorman-linuxkit-${{ steps.vars.outputs.tag }}    
    -
      name: Build and push cordaOS doorman stable tag based on v${{ steps.vars.outputs.tag }}
      id: corda_doorman_stable
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: platforms/r3-corda/images/doorman
        push: true
        tags:  ${{ steps.meta.outputs.tags }}-corda-doorman-linuxkit-stable          
    -
      name: Build and push cordaOS networkmap release tag ${{ steps.vars.outputs.tag }}  
      id: corda_networkmap_release
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: platforms/r3-corda/images/networkmap
        push: true
        tags: ${{ steps.meta.outputs.tags }}-corda-networkmap-linuxkit-${{ steps.vars.outputs.tag }}    
    -
      name: Build and push cordaOS networkmap stable tag based on v${{ steps.vars.outputs.tag }}
      id: corda_networkmap_stable
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: platforms/r3-corda/images/networkmap
        push: true
        tags:  ${{ steps.meta.outputs.tags }}-corda-networkmap-linuxkit-stable    
    -
      name: Build and push cordaOS node release tag ${{ steps.vars.outputs.tag }}  
      id: corda_node_release
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: platforms/r3-corda/images/Dockerfile-corda-tls
        push: true
        tags: ${{ steps.meta.outputs.tags }}-corda-${{ steps.vars.outputs.tag }}    
    -
      name: Build and push cordaOS node stable tag based on v${{ steps.vars.outputs.tag }}
      id: corda_node_stable
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: platforms/r3-corda/images/Dockerfile-corda-tls
        push: true
        tags:  ${{ steps.meta.outputs.tags }}-corda-stable    

  quorum-latest: 
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to the container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    -
      name: Build and push supplychain app latest
      id: quorum_supplychain_latest
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: examples/supplychain-app/quorum/express_nodeJS
        push: true
        tags: ${{ steps.meta.outputs.tags }}-supplychain-quorum-express-app-latest            

  quorum-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}      
    -
      name: Login to the container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    -
      name: Build and push supplychain app release
      id: quorum_supplychain_release
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: examples/supplychain-app/quorum/express_nodeJS
        push: true
        tags: ${{ steps.meta.outputs.tags }}-supplychain-quorum-express-app-${{ steps.vars.outputs.tag }}     
    -
      name: Build and push supplychain app stable
      id: quorum_supplychain_stable
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: examples/supplychain-app/quorum/express_nodeJS
        push: true
        tags: ${{ steps.meta.outputs.tags }}-supplychain-quorum-express-app-stable   
